### ISSUE TITLE
Error on python setup.py install

### ISSUE THREAD

**Issue by ortasa** [cvangysel/pytrec_eval#1]
Good Morning,

When I run :"python setup.py install" I get the following error:
"error: command 'gcc' failed with exit status 1. "
I would  be grateful if you  have a direction what is the problem 

The installation log: 
[install_log.txt](https://github.com/cvangysel/pytrec_eval/files/1720127/install_log.txt)

Thanks in advance, 
Ortal

**Comment by SyedMuhammadAli** [comment]
I have a similar problem with the pytrec_eval_ext build:

Collecting pytrec_eval
  Using cached https://files.pythonhosted.org/packages/ec/ef/93ecabb71ab5c015d23b35751375a1acdce30f8fc00c4a54b4b184814b6c/pytrec_eval-0.3.tar.gz
Building wheels for collected packages: pytrec-eval
  Running setup.py bdist_wheel for pytrec-eval ... error
  Complete output from command c:\users\myu\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\myu\\AppData\\Local\\Temp\\pip-install-isoylhrd\\pytrec-eval\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\myu\AppData\Local\Temp\pip-wheel-n3yrnnbi --python-tag cp35:
  Fetching trec_eval from https://github.com/usnistgov/trec_eval/archive/v9.0.5.zip.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\pytrec_eval
  copying py\__init__.py -> build\lib.win-amd64-3.5\pytrec_eval
  running build_ext
  building 'pytrec_eval_ext' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

  ----------------------------------------
  Failed building wheel for pytrec-eval
  Running setup.py clean for pytrec-eval
Failed to build pytrec-eval
textract 1.6.1 has requirement six==1.10.0, but you'll have six 1.11.0 which is incompatible.
Installing collected packages: pytrec-eval
  Running setup.py install for pytrec-eval ... error
    Complete output from command c:\users\myu\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\myu\\AppData\\Local\\Temp\\pip-install-isoylhrd\\pytrec-eval\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\myu\AppData\Local\Temp\pip-record-887ji8jd\install-record.txt --single-version-externally-managed --compile:
    Fetching trec_eval from https://github.com/usnistgov/trec_eval/archive/v9.0.5.zip.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\pytrec_eval
    copying py\__init__.py -> build\lib.win-amd64-3.5\pytrec_eval
    running build_ext
    building 'pytrec_eval_ext' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\users\myu\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\myu\\AppData\\Local\\Temp\\pip-install-isoylhrd\\pytrec-eval\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\myu\AppData\Local\Temp\pip-record-887ji8jd\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\myu\AppData\Local\Temp\pip-install-isoylhrd\pytrec-eval\

**Comment by cvangysel** [comment]
These are two separate problems.

@ortasa I suspect that you're compiler is using the Python 2 headers/libraries, whereas Python 3 is required.
@SyedMuhammadAli Support for installing pytrec_eval on Windows (outside of Cygwin) is currently not provided. If you manage to get it working, please send a PR with the appropriate fixes.

I'm closing this issue. Please feel free to re-open if you have follow-up questions.
