### ISSUE TITLE
Qrel Relevance scores between 1 to 5

### ISSUE THREAD

**Issue by amirj** [cvangysel/pytrec_eval#4]
Is it right to set qrel relevance scores to sometimg between 1 to 5?
1 means less relevant and 5 means high relevant.
I’m going to use ndcg measure

**Comment by cvangysel** [comment]
Yep, that's generally how it works.

The value of the relevance level gets used in NDCG as the input to an exponential function (https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Normalized_DCG). Be sure to take that into account when designing your experiments.
