### ISSUE TITLE
error when installing using pip

### ISSUE THREAD

**Issue by issam-hub** [cvangysel/pytrec_eval#42]
hello everyone, so basically i'm using windows and i'm trying to install python-terrier and since pytrec_eval is one of the dependencies, there is this error that appears when installing it and break the whole thing:
`
raise ValueError("path '%s' cannot be absolute" % pathname)
      ValueError: path '/tmp/tmpgd7izyps/trec_eval-9.0.8/convert_zscores.c' cannot be absolute
`
any solutions ??

**Comment by seanmacavaney** [comment]
It's unexpected that it's building from source, given the binaries are distributed on pypi. Which Python version and OS version are you using?

**Comment by issam-hub** [comment]
windows 10 and python 3.11.1

**Comment by seanmacavaney** [comment]
It looks like there are builds available for various linux distributions on py11, but not Windows. We should certainly add them, but I'm not sure how soon it will happen. Any chance you could bump down to Python 3.10 for the time being?

Source: https://pypi.org/project/pytrec-eval-terrier/#files

**Comment by issam-hub** [comment]
ah ok, so now if i switch to python 3.10 it will install normal right ?

**Comment by seanmacavaney** [comment]
It should -- it's just that there's not a pre-built Windows binary for Python 11, so it tries to build from scratch. And that process can be tricky/error-prone due to differences in the environment (e.g., which compilers are installed, etc.)

But there are pre-built Windows binaries for Python 3.7-3.10.

**Comment by issam-hub** [comment]
alright, thanks for the help
